REM Copyright (C) 2008, International Business Machines Corporation and others. All Rights Reserved.
svn revert source\common\unicode\brkiter.h
svn revert source\common\unicode\caniter.h
svn revert source\common\unicode\chariter.h
svn revert source\common\unicode\dbbi.h
svn revert source\common\unicode\docmain.h
svn revert source\common\unicode\locid.h
svn revert source\common\unicode\normlzr.h
svn revert source\common\unicode\parseerr.h
svn revert source\common\unicode\parsepos.h
svn revert source\common\unicode\platform.h.in
svn revert source\common\unicode\ppalmos.h
svn revert source\common\unicode\putil.h
svn revert source\common\unicode\pwin32.h
svn revert source\common\unicode\rbbi.h
svn revert source\common\unicode\rep.h
svn revert source\common\unicode\resbund.h
svn revert source\common\unicode\schriter.h
svn revert source\common\unicode\strenum.h
svn revert source\common\unicode\symtable.h
svn revert source\common\unicode\ubidi.h
svn revert source\common\unicode\ubrk.h
svn revert source\common\unicode\ucasemap.h
svn revert source\common\unicode\ucat.h
svn revert source\common\unicode\uchar.h
svn revert source\common\unicode\uchriter.h
svn revert source\common\unicode\uclean.h
svn revert source\common\unicode\ucnv.h
svn revert source\common\unicode\ucnv_cb.h
svn revert source\common\unicode\ucnv_err.h
svn revert source\common\unicode\uconfig.h
svn revert source\common\unicode\udata.h
svn revert source\common\unicode\udeprctd.h
svn revert source\common\unicode\udraft.h
svn revert source\common\unicode\uenum.h
svn revert source\common\unicode\uidna.h
svn revert source\common\unicode\uintrnal.h
svn revert source\common\unicode\uiter.h
svn revert source\common\unicode\uloc.h
svn revert source\common\unicode\umachine.h
svn revert source\common\unicode\umisc.h
svn revert source\common\unicode\unifilt.h
svn revert source\common\unicode\unifunct.h
svn revert source\common\unicode\unimatch.h
svn revert source\common\unicode\uniset.h
svn revert source\common\unicode\unistr.h
svn revert source\common\unicode\unorm.h
svn revert source\common\unicode\uobject.h
svn revert source\common\unicode\uobslete.h
svn revert source\common\unicode\urename.h
svn revert source\common\unicode\urep.h
svn revert source\common\unicode\ures.h
svn revert source\common\unicode\uscript.h
svn revert source\common\unicode\uset.h
svn revert source\common\unicode\usetiter.h
svn revert source\common\unicode\ushape.h
svn revert source\common\unicode\usprep.h
svn revert source\common\unicode\ustring.h
svn revert source\common\unicode\usystem.h
svn revert source\common\unicode\utext.h
svn revert source\common\unicode\utf.h
svn revert source\common\unicode\utf16.h
svn revert source\common\unicode\utf32.h
svn revert source\common\unicode\utf8.h
svn revert source\common\unicode\utf_old.h
svn revert source\common\unicode\utrace.h
svn revert source\common\unicode\utypes.h
svn revert source\common\unicode\uversion.h
svn revert source\i18n\unicode\basictz.h
svn revert source\i18n\unicode\calendar.h
svn revert source\i18n\unicode\choicfmt.h
svn revert source\i18n\unicode\coleitr.h
svn revert source\i18n\unicode\coll.h
svn revert source\i18n\unicode\curramt.h
svn revert source\i18n\unicode\currunit.h
svn revert source\i18n\unicode\datefmt.h
svn revert source\i18n\unicode\dcfmtsym.h
svn revert source\i18n\unicode\decimfmt.h
svn revert source\i18n\unicode\dtfmtsym.h
svn revert source\i18n\unicode\dtptngen.h
svn revert source\i18n\unicode\dtrule.h
svn revert source\i18n\unicode\fieldpos.h
svn revert source\i18n\unicode\fmtable.h
svn revert source\i18n\unicode\format.h
svn revert source\i18n\unicode\gregocal.h
svn revert source\i18n\unicode\measfmt.h
svn revert source\i18n\unicode\measunit.h
svn revert source\i18n\unicode\measure.h
svn revert source\i18n\unicode\msgfmt.h
svn revert source\i18n\unicode\numfmt.h
svn revert source\i18n\unicode\plurfmt.h
svn revert source\i18n\unicode\plurrule.h
svn revert source\i18n\unicode\rbnf.h
svn revert source\i18n\unicode\rbtz.h
svn revert source\i18n\unicode\regex.h
svn revert source\i18n\unicode\search.h
svn revert source\i18n\unicode\simpletz.h
svn revert source\i18n\unicode\smpdtfmt.h
svn revert source\i18n\unicode\sortkey.h
svn revert source\i18n\unicode\stsearch.h
svn revert source\i18n\unicode\tblcoll.h
svn revert source\i18n\unicode\timezone.h
svn revert source\i18n\unicode\translit.h
svn revert source\i18n\unicode\tzrule.h
svn revert source\i18n\unicode\tztrans.h
svn revert source\i18n\unicode\ucal.h
svn revert source\i18n\unicode\ucol.h
svn revert source\i18n\unicode\ucoleitr.h
svn revert source\i18n\unicode\ucsdet.h
svn revert source\i18n\unicode\ucurr.h
svn revert source\i18n\unicode\udat.h
svn revert source\i18n\unicode\udatpg.h
svn revert source\i18n\unicode\ulocdata.h
svn revert source\i18n\unicode\umsg.h
svn revert source\i18n\unicode\unirepl.h
svn revert source\i18n\unicode\unum.h
svn revert source\i18n\unicode\uregex.h
svn revert source\i18n\unicode\usearch.h
svn revert source\i18n\unicode\utmscale.h
svn revert source\i18n\unicode\utrans.h
svn revert source\i18n\unicode\vtzone.h
svn revert source\io\unicode\ustdio.h
svn revert source\io\unicode\ustream.h
